### ISSUE TITLE
iOS Konvertierung

### ISSUE THREAD

**Issue by studio255** [idiomReplaceX/IdiomReplaceX-app#1]
Ich habe versucht das Projekt in XCode zu öffnen oder zu importieren. Ich bin aber gescheitert. Direkt mi XCode geht es nicht auf. Wenn ich ein neues Projekt anlege - welche Spracheinstellungen? SwiftUI, Storyboard und SwiftUI App oder UIKit App Delegate? Dann habe ich ein neues Projekt mit einem leeren Template. Wie kriege ich das nun mit den anderen Files verheiratet. Gibt es da ein How-To?

**Comment by studio255** [comment]
Habe es nun aufbekommen - Flutter heißt das Ding ja. 

Note! Unlike Android studio, flutter isn't supported to XCode yet, you have to open iOS folder of Flutter project only and solely.

1- Open XCode

2- Select 'Open existing Projects'

3- Search your project through search bar in window or search manually through directory.

4- From your Flutter Project, open the iOS folder.

And here we go! You have opened it.

**Comment by studio255** [comment]
Jetzt gibt es folgende Fehler (siehe Screenshot)
<img width="497" alt="Bildschirmfoto 2022-07-12 um 18 31 22" src="https://user-images.githubusercontent.com/3940053/178545504-3d3839d7-7b95-4312-a385-89738119147b.png">
r

**Comment by akohlbecker** [comment]
Hier wird dein Problem diskutiert: https://stackoverflow.com/questions/57901358/error-could-not-find-included-file-pods-target-support-files-pods-runner-pods anscheinend gibt es zwei verschiedene Lösungsansätzte - musst du ev. ausprobieren.

Gefunden per https://duckduckgo.com/?t=ffab&q=XCODE+futter+unable+to+find+included+File+Pods%2Ftarget&ia=web

**Comment by studio255** [comment]
Flutter installiert, cocoa installtiert, dann ...
Found "Xcode 12.5.1, Build version 12E507". Xcode 13 or greater is required to develop for iOS.
Encountered error while building for device.
ich muss erst das ganze betriebssystem updaten?

**Comment by studio255** [comment]
Habe jetzt flutter 2.10.5 geladen und alles per command line flutter build ios gestartet, fehler

-----

Error (Xcode): No profiles for 'com.pichillilorenzo.flutter-browser' were found: Xcode couldn't find any iOS App Development
provisioning profiles matching 'com.pichillilorenzo.flutter-browser'. Automatic signing is disabled and unable to generate a
profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.

It appears that there was a problem signing your application prior to installation on the device.

Verify that the Bundle Identifier in your project is your signing id in Xcode
  open ios/Runner.xcworkspace

Also try selecting 'Product > Build' to fix the problem:
Encountered error while building for device.
-----

... dann per xcode einen build gemacht. läuft dann eine weile, dann build failed.

Command PhaseScriptExecution failed with a nonzero exit code


lib/project_info_popup.dart:12:8: Error: Error when reading '../../../../flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.4/lib/url_launcher_string.dart': No such file or directory
import 'package:url_launcher/url_launcher_string.dart';
       ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/platform-3.0.0/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
      io.Platform.packageRoot; // ignore: deprecated_member_use
                  ^^^^^^^^^^^
lib/project_info_popup.dart:42:51: Error: The method 'canLaunchUrlString' isn't defined for the class '_ProjectInfoPopupState'.
 - '_ProjectInfoPopupState' is from 'package:flutter_browser/project_info_popup.dart' ('lib/project_info_popup.dart').
Try correcting the name to the name of an existing method, or defining a method named 'canLaunchUrlString'.
                      var urlIsLaunchable = await canLaunchUrlString(url);
                                                  ^^^^^^^^^^^^^^^^^^
lib/project_info_popup.dart:44:31: Error: The method 'launchUrlString' isn't defined for the class '_ProjectInfoPopupState'.
 - '_ProjectInfoPopupState' is from 'package:flutter_browser/project_info_popup.dart' ('lib/project_info_popup.dart').
Try correcting the name to the name of an existing method, or defining a method named 'launchUrlString'.
                        await launchUrlString(url); //launch is from url_launcher package to launch URL
                              ^^^^^^^^^^^^^^^
lib/project_info_popup.dart:73:51: Error: The method 'canLaunchUrlString' isn't defined for the class '_ProjectInfoPopupState'.
 - '_ProjectInfoPopupState' is from 'package:flutter_browser/project_info_popup.dart' ('lib/project_info_popup.dart').
Try correcting the name to the name of an existing method, or defining a method named 'canLaunchUrlString'.
                      var urlIsLaunchable = await canLaunchUrlString(url);
                                                  ^^^^^^^^^^^^^^^^^^
lib/project_info_popup.dart:75:31: Error: The method 'launchUrlString' isn't defined for the class '_ProjectInfoPopupState'.
 - '_ProjectInfoPopupState' is from 'package:flutter_browser/project_info_popup.dart' ('lib/project_info_popup.dart').
Try correcting the name to the name of an existing method, or defining a method named 'launchUrlString'.
                        await launchUrlString(url); //launch is from url_launcher package to launch URL
                              ^^^^^^^^^^^^^^^
lib/project_info_popup.dart:99:51: Error: The method 'canLaunchUrlString' isn't defined for the class '_ProjectInfoPopupState'.
 - '_ProjectInfoPopupState' is from 'package:flutter_browser/project_info_popup.dart' ('lib/project_info_popup.dart').
Try correcting the name to the name of an existing method, or defining a method named 'canLaunchUrlString'.
                      var urlIsLaunchable = await canLaunchUrlString(url);
                                                  ^^^^^^^^^^^^^^^^^^
lib/project_info_popup.dart:101:31: Error: The method 'launchUrlString' isn't defined for the class '_ProjectInfoPopupState'.
 - '_ProjectInfoPopupState' is from 'package:flutter_browser/project_info_popup.dart' ('lib/project_info_popup.dart').
Try correcting the name to the name of an existing method, or defining a method named 'launchUrlString'.
                        await launchUrlString(url); //launch is from url_launcher package to launch URL
                              ^^^^^^^^^^^^^^^
Failed to package /Users/vertov/Documents/workspace/idiom-app/IdiomReplaceX-app.
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by akohlbecker** [comment]
das sieht eigentlich ganz gut aus. Da fehlt das ` 'package:url_launcher/url_launcher_string.dart';` paket, bin gerade schon dabei das zu fixen.....

**Comment by akohlbecker** [comment]
missing package added with commit 838e5355a2b282d4e343a0a4af4ac313f18061c6 and fixing other problems.

please test again

**Comment by studio255** [comment]
Habe hoffentlich alles richtig gezogen, nochmals flutter build ausgeführt und dann beim xcode build:

Building flutter tool...
lib/project_info_popup.dart:12:8: Error: Error when reading '../../../../flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.4/lib/url_launcher_string.dart': No such file or directory
import 'package:url_launcher/url_launcher_string.dart';
       ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/platform-3.0.0/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
      io.Platform.packageRoot; // ignore: deprecated_member_use
                  ^^^^^^^^^^^
lib/project_info_popup.dart:42:51: Error: The method 'canLaunchUrlString' isn't defined for the class '_ProjectInfoPopupState'.
 - '_ProjectInfoPopupState' is from 'package:flutter_browser/project_info_popup.dart' ('lib/project_info_popup.dart').
Try correcting the name to the name of an existing method, or defining a method named 'canLaunchUrlString'.
                      var urlIsLaunchable = await canLaunchUrlString(url);
                                                  ^^^^^^^^^^^^^^^^^^
lib/project_info_popup.dart:44:31: Error: The method 'launchUrlString' isn't defined for the class '_ProjectInfoPopupState'.
 - '_ProjectInfoPopupState' is from 'package:flutter_browser/project_info_popup.dart' ('lib/project_info_popup.dart').
Try correcting the name to the name of an existing method, or defining a method named 'launchUrlString'.
                        await launchUrlString(url); //launch is from url_launcher package to launch URL
                              ^^^^^^^^^^^^^^^
lib/project_info_popup.dart:73:51: Error: The method 'canLaunchUrlString' isn't defined for the class '_ProjectInfoPopupState'.
 - '_ProjectInfoPopupState' is from 'package:flutter_browser/project_info_popup.dart' ('lib/project_info_popup.dart').
Try correcting the name to the name of an existing method, or defining a method named 'canLaunchUrlString'.
                      var urlIsLaunchable = await canLaunchUrlString(url);
                                                  ^^^^^^^^^^^^^^^^^^
lib/project_info_popup.dart:75:31: Error: The method 'launchUrlString' isn't defined for the class '_ProjectInfoPopupState'.
 - '_ProjectInfoPopupState' is from 'package:flutter_browser/project_info_popup.dart' ('lib/project_info_popup.dart').
Try correcting the name to the name of an existing method, or defining a method named 'launchUrlString'.
                        await launchUrlString(url); //launch is from url_launcher package to launch URL
                              ^^^^^^^^^^^^^^^
lib/project_info_popup.dart:99:51: Error: The method 'canLaunchUrlString' isn't defined for the class '_ProjectInfoPopupState'.
 - '_ProjectInfoPopupState' is from 'package:flutter_browser/project_info_popup.dart' ('lib/project_info_popup.dart').
Try correcting the name to the name of an existing method, or defining a method named 'canLaunchUrlString'.
                      var urlIsLaunchable = await canLaunchUrlString(url);
                                                  ^^^^^^^^^^^^^^^^^^
lib/project_info_popup.dart:101:31: Error: The method 'launchUrlString' isn't defined for the class '_ProjectInfoPopupState'.
 - '_ProjectInfoPopupState' is from 'package:flutter_browser/project_info_popup.dart' ('lib/project_info_popup.dart').
Try correcting the name to the name of an existing method, or defining a method named 'launchUrlString'.
                        await launchUrlString(url); //launch is from url_launcher package to launch URL
                              ^^^^^^^^^^^^^^^
Failed to package /Users/vertov/Documents/workspace/idiom-app/IdiomReplaceX-app.
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by akohlbecker** [comment]
Welche flutter version verwendest du? Das Projekt ist derzeit für Flutter version 2.5.3 ausgelegt.

Du könntest in der Project-Root mal `flutter doctor -v` laufen lassen und die Diagnose hier posten.

**Comment by studio255** [comment]
> Habe jetzt flutter 2.10.5 geladen, müsste das klappen?

**Comment by kasoft** [comment]
[✓] Flutter (Channel unknown, 3.0.5, on macOS 11.6.1 20G224 darwin-x64, locale
    de-DE)
    • Flutter version 3.0.5 at /Users/vertov/flutter
    • Upstream repository unknown
    • Framework revision f1875d570e (8 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ✗ Flutter requires Xcode 13 or higher.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • macOS 11.6.1 20G224 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 4 categories.

**Comment by studio255** [comment]
OK, das war ein guter Hinweis. Ich hatte extra Version 3 gelöscht und 2.10 installiert. Da muss zwischendurch einfach ein Update gelaufen sein. Nun wieder "flutter build ios, dann pod install, dann build mit xcode". Jetzt kommt nur noch 1 Fehler direkt aus dem Code:

Datei: GeneratedPluginRegistrant.m
--> Module 'path_provider' not found
Zeile 30

```
#if __has_include(<path_provider/FLTPathProviderPlugin.h>)
#import <path_provider/FLTPathProviderPlugin.h>
#else
@import path_provider;
#endif
```

**Comment by akohlbecker** [comment]
Eigentlich ist das das Package in der `pubspec.yaml`  als `path_provider: ^2.0.1` eingetragen und sollte dementsprechend in der  `pubspec.lock` aufgeführt sein. Vielleicht ist deine `pubspec.lock` irgendwie verändert worden. Check doch mal ob du diesen Eintrag unten  findest und ob sie sich von der in GitHub unterscheidet: `git diff origin/main pubspec.lock`

~~~
 path_provider_ios:
    dependency: transitive
    description:
      name: path_provider_ios
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.7"
~~~

**Comment by studio255** [comment]
Hier leider keine Lösung. Die Version war korrekt, die Datei befindet sich aber eine Ebene über dem Ordner ios (in welchem ich arbeite und builde). Habe auch nochmals per pull den letzten Stand gezogen, nix. gleicher Fehler

<img width="1065" alt="Bildschirmfoto 2022-07-22 um 10 41 46" src="https://user-images.githubusercontent.com/3940053/180400354-611aa0f2-5aca-46cd-b4b7-a192ad83cda4.png">

**Comment by studio255** [comment]
Achje, jetzt habe ich ein wenig probiert, nun der folgende Fehler ...
<img width="1001" alt="Bildschirmfoto 2022-07-22 um 10 53 45" src="https://user-images.githubusercontent.com/3940053/180402755-ac6dd467-1a48-4c1c-893c-eec9aafb2991.png">

**Comment by studio255** [comment]
Update zur Fehlersuche. Ich habe nun flutter clean, flutter build ios usw. öfters probiert und auch die Fehlermeldungen gegooglet, komme aber aktuell nicht weiter. Es scheint ein Problem der Verknüpfung von Paketen zu sein und eventuell mit der iOS Target Version zusammen zu hängen (eventuell verschieden im Flutter Projekt und im Xcode, aktuell 9.0).

Entweder bekomme ich den Fehler path_provider oder das flutter_downloader fehlt. Was ich nicht verstehe ...
- ich habe flutter in einem separaten Folder auf meiner HD und mit einem PATH zugänglich gemacht, ist das OK?
- Es gibt Runner.xcodeproj und Runner.xcworkspace (manche im Netz sagen der Fehler lässt sich lösen wenn man xcworkspace im xcode öffnet. bringt nix.
- folgende Hinweise kommen von pod die ich nicht verstehe: [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
- Auch flutter bringt bei build eine meldung in rot: The plugin `flutter_downloader` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command. 
- "Podfile" wird nicht automatisch erzeugt, warum? das scheint mir die entsprechung zu pubspec.yaml zu sein, welche im xcode gar keine bedeutung hat, ich arbeite ja nur im ios folder
- die Datei Frameworks/Pods_Runner.framework wird im Xcode in rot als fehlend angezeigt

Soweit so verloren ....

**Comment by studio255** [comment]
Neuer Versuch mit Bitrise, ist nicht das ganze Log aber ...

Agent version:	1.44.1
Hostname:	vm-osx-xcode-13.2.x-g2.4core-e3c2561f-b310-45c1-90fe-2bbc6d5382f3
Nodename:	LAS1-vFW01-gen2-mmg4-10-92-100-96
Start time:	2022-08-30T16:49:48Z
$ bitrise "run" "--config" "/var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/bitrise-agent852560514/bitrise.yml" "--inventory" "/var/folders/11/nh0v1jld7zd7b9zqm1774gtm0000gn/T/bitrise-agent852560514/bitrise.secrets.yml" "--json-params-base64" "eyJ3b3JrZmxvdyI6InByaW1hcnkifQ=="

  ██████╗ ██╗████████╗██████╗ ██╗███████╗███████╗
  ██╔══██╗██║╚══██╔══╝██╔══██╗██║██╔════╝██╔════╝
  ██████╔╝██║   ██║   ██████╔╝██║███████╗█████╗
  ██╔══██╗██║   ██║   ██╔══██╗██║╚════██║██╔══╝
  ██████╔╝██║   ██║   ██║  ██║██║███████║███████╗
  ╚═════╝ ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝╚══════╝


This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
The plugin `flutter_downloader` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.
Run: completing test command failed: exit status 1
Bad state: not started
Run: completing conversion command failed: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | flutter-test@1 (exit code: 1)                                 | 14.85 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...ithub.com/bitrise-steplib/bitrise-step-flutter-test/issues |
| Source: https://github.com/bitrise-steplib/bitrise-step-flutter-test         |
+---+---------------------------------------------------------------+----------+

**Comment by studio255** [comment]
Mit Flutter 2.5.3 klappt das nun. Nach einem Updates meines macOS und mit XCode 13 und einigen weiteren Einstellungen läuft die App auch auf meinem iPhone 8 mit iOS 15
