### ISSUE TITLE
Update App Icon to new design

### ISSUE THREAD

**Issue by akohlbecker** [idiomReplaceX/IdiomReplaceX-app#10]
The app-icons for Android and iOS should be updated to the new logo design:

locations:

* iOS: `AppIcons/Assets.xcassets`
* Android: `AppIcons/android`

**Comment by akohlbecker** [comment]
Nils, can you provide the icons for iOS?

**Comment by studio255** [comment]
Ja! Die baue ich ein bevor ich die app nochmals einreiche

**Comment by kasoft** [comment]
Anbei mal das Set, ich baue die noch ein ...
[AppIcons_irx.zip](https://github.com/idiomReplaceX/IdiomReplaceX-app/files/9910240/AppIcons_irx.zip)

**Comment by studio255** [comment]
Hier ein Set mit iOS und Android Icons
[AppIcons_irx2.zip](https://github.com/idiomReplaceX/IdiomReplaceX-app/files/9910293/AppIcons_irx2.zip)
