### ISSUE TITLE
URL like addresses should be connected not "searched"

### ISSUE THREAD

**Issue by licaon-kter** [idiomReplaceX/IdiomReplaceX-app#2]
I can't have it access any address if I write them in the URL input box, it just "always searches". eg. `f-droid.org` is replaced with `searchengine.com/?q=f-droid.org`

@akohlbecker 
> A bit old school behavior of the Flutter Browser, you need to type the scheme part of the URL like https://.... to avoid the search engine.

Oh, come on, ain't nobody got time for that, if it looks like an address `domain.tld` just try to open it! :)

This is also a privacy leak, imho.

**Comment by akohlbecker** [comment]
Agreed! This is a UX and privacy issue that exists already in the original Flutter Browser App (https://github.com/pichillilorenzo/flutter_browser_app),   I will still fix this issue for the IdomReplaceX app when I have time.

**Comment by studio255** [comment]
Ich habe das auch noch in der iOS App genauso, das eingeben einer URL ist extrem tricky da auch bei der URL sofort die Suchseite aufgeht. Es ist auch kaum möglich eine URL zu löschen. Die App setzt immer wieder die aktuelle URL in die Adresszeile (wenn man es nicht schafft, allles auf einmal zu löschen ...)

**Comment by akohlbecker** [comment]
fixed with 8496827
