### ISSUE TITLE
Position Filter / Layout

### ISSUE THREAD

**Issue by studio255** [idiomReplaceX/IdiomReplaceX-app#5]
Kann der Filter anstatt zu "schweben" einfach untern im Bildschirm einen Block bilden? Kann ich das per CSS einstellen und anpassen?

**Comment by akohlbecker** [comment]
Das müssen wir besprechen .....

**Comment by akohlbecker** [comment]
hier wäre das z.B. ein Problem: 

![image](https://user-images.githubusercontent.com/809346/189503129-c5253316-5410-47cd-910f-895d8d88d2fd.png)

**Comment by akohlbecker** [comment]
ich schlage vor dieses Ticket zu schließen, was meinst du?

**Comment by studio255** [comment]
Nicht mehr nötig
