### ISSUE TITLE
Crash wenn kein Tab offen

### ISSUE THREAD

**Issue by studio255** [idiomReplaceX/IdiomReplaceX-app#6]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |  2.5.3             |
| App version          |   1.1            |
| Android version      |     -          |
| iOS version          |    15.6.1           |
| Xcode version        |     13.4.1          |

Device information: iphone 8

## Description

Wenn alle Tabs geschlossen werden und ich die App danach erneut starte, gibt es einen crash (vermutlich da kein tab offen ...)

**Comment by kasoft** [comment]
Update zum "Link wird in Safari geöffent". Wenn ich die Spiegel App auf dem Handy habe, dann werden Links von Spiegel.de in der App geöffnet. Alle anderen Links klappen so. Ich denke das Problem können wir hinten anstellen ...

**Comment by akohlbecker** [comment]
hast du einen Stacktrace oder ähnliches?

Wie lässt sich das so reproduzieren

1. alle Tabs schließen
2. App beenden oder nur in den Hintergrund?
3. App über Icon in den Vordergrund oder neu starten?

**Comment by studio255** [comment]
Ist bei mir nach eimem Installieren der App über den AppStore per TestFlight nicht mehr aufgetreten.
