### ISSUE TITLE
Overlay liegt hinter Seiteninhalt

### ISSUE THREAD

**Issue by studio255** [idiomReplaceX/IdiomReplaceX-app#7]
Das Overlay für die Filterwahl liegt immer mal wieder hinter einem Inhalt der Seite. Zum Beispiel auf Karlsruhe.de - siehe Screenshot. 

![IMG_9305](https://user-images.githubusercontent.com/3940053/189171662-f78a8938-55e0-41d5-adf4-cabede8139fd.PNG)

**Comment by akohlbecker** [comment]
Fixed by idiomReplaceX/idiomreplacex-client@0343f3c and idiomReplaceX/idiomreplacex-client@1722bb9
